version: '2.0'

volumes:
  db:
    driver: local

services:
  app:
    build: .
    environment:
      DB_DRIVER: pdo_sqlite
      DB_PATH: /data/data.sqlite
    volumes:
      - "db:/data"
      - ".:/var/www"
  web:
    image: nginx:1.11
    ports:
    - "80:80"
    volumes:
    - "./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    - "./web:/var/www/web:ro"
    depends_on:
    - app
